---
# This file contains tasks for building and pushing the Docker image

- name: Log in to Docker Hub
  community.docker.docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"

- name: Build Docker Image
  community.docker.docker_image:
    build:
      path: "{{ playbook_dir }}/files"
    name: "{{ dockerhub_username }}/{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"

- name: Push Docker Image to Docker Hub
  community.docker.docker_image:
    name: "{{ dockerhub_username }}/{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    push: true
    source: local

