---
dockerhub_username: "username"  # Replace with your Docker Hub username
dockerhub_password: "password"  # Replace with your Docker Hub password
docker_image_name: "webapp"
docker_image_tag: "latest"

